"use client";
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
const links=[['Home','/'],['The shake','/formula'],['The honey','/honey'],['Our story','/about'],['Teams','/wholesale']];
export function Header(){const[open,setOpen]=useState(false);const path=usePathname();
 useEffect(()=>{setOpen(false)},[path]);
 useEffect(()=>{const desktop=window.matchMedia('(min-width: 1101px)');const close=()=>{if(desktop.matches)setOpen(false)};desktop.addEventListener('change',close);return()=>desktop.removeEventListener('change',close)},[]);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open]);
 return <><a className="skip-link" href="#main">Skip to content</a><div className="header-wrap"><header className="header shell"><a className="brand" href="/" aria-label="beeast home"><span className="brand-mark"><img src="/assets/beeast-logo.png" alt="beeast" width="1774" height="887"/></span></a><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label,href])=><a key={href} href={href} aria-current={path===href?'page':undefined}>{label}</a>)}</nav><a className="nav-cta" href="/#waitlist" onClick={()=>setOpen(false)}>Join waitlist <span className="chevron" aria-hidden="true"/></a><button className="menu-toggle" type="button" aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?'Close':'Menu'} <span aria-hidden="true">{open?'−':'+'}</span></button>{open&&<nav id="mobile-nav" className="mobile-panel" aria-label="Mobile navigation">{links.map(([label,href],i)=><a key={href} href={href} aria-current={path===href?'page':undefined} onClick={()=>setOpen(false)}><span className="mono">0{i+1}</span>{label}<span className="chevron" aria-hidden="true"/></a>)}</nav>}</header></div></>;
}
export function Footer(){return <footer className="footer shell"><div className="footer-top"><a className="brand footer-brand" href="/" aria-label="beeast home"><img src="/assets/beeast-logo.png" alt="beeast" width="1774" height="887"/></a><p>Look Beeyond<br/>the Label.</p><nav aria-label="Footer navigation"><a href="/formula">The shake</a><a href="/honey">The honey</a><a href="/process">Our process</a><a href="/about">Our story</a><a href="/wholesale">Teams & Facilities</a><a href="mailto:contact@drinktnat.com">contact@drinktnat.com</a><a href="/privacy">Privacy</a></nav></div><div className="footer-bottom mono"><span>© 2026 beeast</span><span>Stuart, Florida</span><span>In development. Not yet available.</span></div></footer>}