"use client";
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
const links=[['Home','/'],['The formula','/formula'],['The process','/process'],['About Us','/about'],['Wholesale','/wholesale']];
export function Header(){const[open,setOpen]=useState(false);const path=usePathname();
 useEffect(()=>{setOpen(false)},[path]);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open]);
 return <><a className="skip-link" href="#main">Skip to content</a><div className="header-wrap"><header className="header shell"><a className="brand" href="/" aria-label="TNAT home"><span className="brand-mark"><img src="/assets/tnat-co-horizontal.png" alt="TNAT" width="1983" height="793"/></span></a><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label,href])=><a key={href} href={href} aria-current={path===href?'page':undefined}>{label}</a>)}</nav><a className="nav-cta" href="/#waitlist" onClick={()=>setOpen(false)}>Join waitlist <span aria-hidden="true">↗</span></a><button className="menu-toggle" type="button" aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?'Close':'Menu'} <span aria-hidden="true">{open?'−':'+'}</span></button>{open&&<nav id="mobile-nav" className="mobile-panel" aria-label="Mobile navigation">{links.map(([label,href],i)=><a key={href} href={href} aria-current={path===href?'page':undefined} onClick={()=>setOpen(false)}><span className="mono">0{i+1}</span>{label}<span aria-hidden="true">↗</span></a>)}</nav>}</header></div></>;
}
export function Footer(){return <footer className="footer shell"><div className="footer-top"><a className="brand" href="/" aria-label="TNAT home"><span className="brand-mark"><img src="/assets/tnat-co-horizontal.png" alt="TNAT" width="1983" height="793"/></span></a><p>The future of<br/>protein shakes.</p><nav aria-label="Footer navigation"><a href="/">Home</a><a href="/formula">The formula</a><a href="/about">About Us</a><a href="/wholesale">Wholesale & team inquiries</a><a href="mailto:contact@drinktnat.com">contact@drinktnat.com</a><a href="/privacy">Privacy</a></nav></div><div className="footer-bottom mono"><span>© 2026 Drink TNAT</span><span>Stuart, Florida</span><span>In development. Not yet available.</span></div></footer>}
