import WaitlistForm from './WaitlistForm';
import {Counter,TeamBottles} from './ProductMotion';
export const ingredients = [
 {name:'Filtered water',job:'The base of our chocolate shake.',choice:'Water lets us build the protein, sweetness, and texture ingredient by ingredient.'},
 {name:'Whey protein concentrate',job:'A fast-digesting, complete milk protein, naturally rich in leucine.',choice:'We are sourcing grass-fed whey protein concentrate for a formula targeting 32g of protein per bottle. Supplier specifications and finished-product nutrition still need confirmation.'},
 {name:'Raw Florida honey',job:'Our only sweetener, bringing sweetness and carbohydrate to the shake.',choice:'Florida honey connects our ingredient sourcing to the state we call home. It contributes sugar and calories; it is not a zero-calorie sweetener.'},
 {name:'Cocoa',job:'Dutch-processed cocoa provides the chocolate flavor.',choice:'We build the chocolate profile around cocoa, without artificial flavors.'},
 {name:'Sea salt',job:'A small amount to balance and lift the chocolate.',choice:'It earns its place through flavor. We are not positioning this amount as an electrolyte or hydration benefit.'},
 {name:'Vanilla extract',job:'Rounds the cocoa and deepens the flavor.',choice:'A little vanilla complements the chocolate. Final extract sourcing and specifications are pending.'},
 {name:'Lactase enzyme',job:'Breaks down the lactose that comes with whey, with a lactose-free finished drink as our target.',choice:'Lactase converts lactose into glucose and galactose. The dose, process, and residual lactose must be validated before we can confirm a lactose-free claim. Contains milk.'}
];
export function ColdLife(){return <div className="cold-life"><span className="mono">Made for the fridge</span><p><strong className="mono"><Counter value={45}/></strong><span>days cold<br/><b>Our target</b></span></p><small>Target shelf life for an unopened, refrigerated bottle. Testing must confirm the final shelf life and storage conditions.</small></div>}
export function ColdPositioning({processLink=false}:{processLink?:boolean}){return <div className="cold-positioning"><div><p className="eyebrow">Shorter shelf life. By design.</p><h2><span className="mono"><Counter value={45}/> days cold.</span><sup>*</sup><br/><span>Not 18 months warm.</span></h2></div><div className="cold-positioning-copy"><p className="section-description">We skipped the shelf. We’re building TNAT for the refrigerator, with seven purposeful ingredients and no gums or preservatives in our formula in development.</p><p className="section-description">The short date is the point. We’re evaluating high pressure processing and refrigerated distribution for this formula, with safety and shelf-life validation before launch.</p><p className="fine cold-target">*45 days is our target for an unopened, refrigerated bottle. This is a development goal; testing must confirm the final shelf life and storage conditions.</p>{processLink&&<a className="text-link" href="/process">Explore the planned process <span className="chevron" aria-hidden="true"/></a>}</div></div>}
export function VanillaComingSoon(){return <section className="vanilla-section bone" id="vanilla"><div className="shell section vanilla-inner"><div><p className="eyebrow">The next chapter</p><h2>Vanilla.<br/><span>Coming soon.</span></h2></div><div><p className="section-description">Chocolate leads the way. Vanilla is the next flavor we plan to develop, with the same commitment to a short, considered ingredient list.</p><p className="fine">Planned next. Formula and launch date are not set. Neither flavor is available to buy yet.</p><a className="text-link" href="/#waitlist">Follow the flavor updates <span className="chevron" aria-hidden="true"/></a></div></div></section>}
export function Waitlist(){return <section className="waitlist-section shell" id="waitlist"><div><p className="eyebrow">Coming from Stuart, Florida</p><h2>A shorter label.<br />A new beginning.</h2><p className="section-description">For your training, your routine, and your everyday. Follow the development of our first chocolate shake and hear about launch updates and the first Florida batches.</p></div><WaitlistForm id="footer" /></section>}
export function Numbers(){return <section className="bone"><div className="shell section"><p className="eyebrow">The formulation, in numbers</p><div className="spec-grid"><div><strong><Counter value={32}/>g<span>*</span></strong><span>Protein per bottle</span></div><div><strong><Counter value={7}/></strong><span>Ingredients</span></div><div><strong><Counter value={220}/><span>*</span></strong><span>Calories per bottle</span></div></div><div className="nutrition-secondary mono"><span>4.5g fat*</span><span>15g carbohydrate*</span><span>12g total sugar*</span><span>Includes 10g added sugars (20% DV)*</span><span>295mg sodium*</span><span>3.1g leucine*</span><span>Lactose-free target · pending validation</span></div><p className="fine nutrition-note">*Calculated estimates for a 12 fl oz bottle. Not lab-tested. Final nutrition and formula may change before launch.</p><a className="text-link" href="/formula#nutrition">See the estimated nutrition panel <span className="chevron" aria-hidden="true"/></a></div></section>}
export function Comparison(){return <section className="comparison-section shell section"><div className="section-heading"><div><p className="eyebrow">02 / Turn the bottle around</p><h2>A shorter label.<br/>A different standard.</h2></div><p className="section-description">Compare our seven-ingredient formula with Premier Protein and Fairlife Core Power. Start with what goes into the bottle.</p></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Product comparison; scroll horizontally on small screens"><table className="comparison"><thead><tr><th scope="col">On the label</th><th scope="col" className="ours">TNAT Chocolate<small>Formula in development</small></th><th scope="col">Premier Protein<small>Chocolate shake</small></th><th scope="col">Fairlife Core Power<small>Chocolate · 26g</small></th></tr></thead><tbody>{[
 ['Ingredient count*','7','18','13'],
 ['Protein source','Whey protein concentrate','Milk protein concentrate + calcium caseinate','Ultra-filtered milk'],
 ['Sweeteners','Raw Florida honey','Sucralose + acesulfame potassium','Monk fruit, stevia, sucralose + acesulfame potassium'],
 ['Cellulose gum / gel','None','Both listed','Both listed'],
 ['Carrageenan','None','Listed','Listed'],
 ['Artificial flavors','None','Listed','Not listed']
].map(row=><tr key={row[0]}><th scope="row">{row[0]}</th>{row.slice(1).map((cell,i)=><td className={i===0?'ours':''} key={i}>{cell}</td>)}</tr>)}</tbody></table></div><p className="fine sources">*Counts use top-level label entries: Premier’s vitamin and mineral blend counts as one, its alternative oils as one, and cellulose gel and cellulose gum separately. Grouped flavors count as one. Based on <a href="https://www.premierprotein.com/products/chocolate-protein-shake" target="_blank" rel="noreferrer">Premier Protein</a> and <a href="https://fairlife.com/core-power/chocolate-protein-shake/" target="_blank" rel="noreferrer">Fairlife Core Power</a> manufacturer labels, checked September 23, 2026. Formulas vary by flavor and may change. TNAT’s formula is in development. Ingredient count alone does not establish nutritional quality or safety.</p></section>}
export function TeamSection(){return <section className="team-section"><div className="shell section"><p className="eyebrow">Florida first. On purpose.</p><div className="team-heading"><h2>For the people<br/>stocking the<br/>team fridge.</h2><div><p className="section-description">Seven ingredients you can read out loud. One named protein source. No proprietary blends. A formula your athletes can understand and your staff can evaluate.</p><a className="button team-button" href="/wholesale">Teams & Facilities <span className="chevron" aria-hidden="true"/></a></div></div><TeamBottles/><div className="team-audiences"><article><span className="mono">01 / Colleges & universities</span><p>For strength coaches, team dietitians, and athletic departments assessing their next team-fridge option.</p></article><article><span className="mono">02 / Pro & semi-pro teams</span><p>Start a conversation about your roster, monthly volume, and the documentation your program needs.</p></article><article><span className="mono">03 / Gyms & training facilities</span><p>A refrigerated shake for independent Florida facilities and the athletes who train there.</p></article></div><div className="team-logistics"><h3>A shorter route.<br/>A continuous cold chain.</h3><p>We’re planning in-state refrigerated delivery from production facility to team fridge. Tell us your monthly volume so we can discuss future case pricing and delivery needs without a national freight program.</p></div><p className="fine">Pre-launch inquiries only. Pricing, service areas, delivery schedules, product testing, and third-party certification are not yet confirmed. No university affiliation or endorsement is implied. Individual customers are welcome on the launch waitlist.</p></div></section>}
