import WaitlistForm from './WaitlistForm';
export const ingredients = [
 {name:'Filtered water',amount:'~300 g',job:'The liquid base that carries the protein, cocoa, and cream into a drinkable shake.',choice:'Starting with water lets us build the texture and protein level ingredient by ingredient, while keeping the chocolate flavor at the center.'},
 {name:'Whey protein isolate',amount:'27 g',job:'A concentrated milk-derived protein with all nine essential amino acids. Our grass-fed isolate formula targets 25g of protein per bottle.',choice:'Compared with typical whey concentrate, isolate brings a higher proportion of protein and less lactose. We choose it to keep protein at the center of the formula. Contains milk; sourcing and nutrition are still being confirmed.'},
 {name:'Coconut cream',amount:'15 g',job:'Brings fat, body, and a creamy mouthfeel—the shake part of the protein shake.',choice:'We use cream to build richness without adding gums for thickness. It also contributes saturated fat; this is a texture choice, not a claim that coconut fat is healthier.'},
 {name:'Cocoa',amount:'6 g',job:'Dutch-processed cocoa brings the chocolate flavor, deep color, and rounded cocoa profile.',choice:'Chocolate comes from cocoa in the formula. We are building the flavor around that ingredient without adding artificial flavors.'},
 {name:'Sunflower lecithin',amount:'1.0 g',job:'An emulsifier that helps the coconut cream’s fat mix with the water-based ingredients.',choice:'It has a specific mixing job. We use it without adding gums for thickness. It will not eliminate all settling or separation, so shaking remains part of the experience.'},
 {name:'Sea salt',amount:'0.4 g',job:'A small amount to balance sweetness and round out the cocoa flavor.',choice:'It earns its place through flavor. We are not positioning this amount as an electrolyte or hydration benefit.'},
 {name:'Monk fruit extract',amount:'In testing',job:'Our only sweetener. A little brings sweetness to balance the cocoa; the exact dose is being set through taste trials.',choice:'One sweetener keeps the formula at seven ingredients. We choose monk fruit extract without an artificial-sweetener blend. Final sourcing must preserve that single-ingredient choice.'}
];
export function ColdLife(){return <div className="cold-life"><span className="mono">Made for the fridge</span><p><strong>45</strong><span>days cold<br/><b>Our target</b></span></p><small>Target shelf life for an unopened, refrigerated bottle. Testing must confirm the final shelf life and storage conditions.</small></div>}
export function VanillaComingSoon(){return <section className="vanilla-section bone" id="vanilla"><div className="shell section vanilla-inner"><div><p className="eyebrow">The next chapter</p><h2>Vanilla.<br/><span>Coming soon.</span></h2></div><div><p className="section-description">Chocolate leads the way. Vanilla is the next flavor we plan to develop, with the same commitment to a short, considered ingredient list.</p><p className="fine">Planned next. Formula and launch date are not set. Neither flavor is available to buy yet.</p><a className="text-link" href="/#waitlist">Follow the flavor updates <span aria-hidden="true">↗</span></a></div></div></section>}
export function Waitlist(){return <section className="waitlist-section shell" id="waitlist"><div><p className="eyebrow">Coming from Stuart, Florida</p><h2>A shorter label.<br />A new beginning.</h2><p className="section-description">For your training, your routine, and your everyday. Follow our first chocolate shake, with vanilla planned next, and hear about launch updates and the first batches.</p></div><WaitlistForm id="footer" /></section>}
export function Numbers(){return <section className="bone"><div className="shell section"><p className="eyebrow">The formulation, in numbers</p><div className="spec-grid"><div><strong>25g<span>*</span></strong><span>Protein per bottle</span></div><div><strong>7</strong><span>Proposed ingredients</span></div><div><strong>150<span>*</span></strong><span>Calories per bottle</span></div></div><p className="fine nutrition-note">*Calculated estimates for a 12 fl oz bottle. Not lab-tested. Final nutrition and formula may change before launch.</p></div></section>}
export function Comparison(){return <section className="comparison-section shell section"><div className="section-heading"><div><p className="eyebrow">02 / Turn the bottle around</p><h2>A shorter label.<br/>A different standard.</h2></div><p className="section-description">Compare our seven-ingredient formula with Premier Protein and Fairlife Core Power. Start with what goes into the bottle.</p></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Product comparison; scroll horizontally on small screens"><table className="comparison"><thead><tr><th scope="col">On the label</th><th scope="col" className="ours">TNAT Chocolate<small>Proposed formula</small></th><th scope="col">Premier Protein<small>Chocolate shake</small></th><th scope="col">Fairlife Core Power<small>Chocolate · 26g</small></th></tr></thead><tbody>{[
 ['Ingredient count*','7','20+','13'],
 ['Protein source','Whey protein isolate','Milk protein concentrate + calcium caseinate','Ultra-filtered milk'],
 ['Artificial sweeteners','None — monk fruit only','Sucralose + acesulfame potassium','Sucralose + acesulfame potassium'],
 ['Cellulose gum / gel','None','Both listed','Both listed'],
 ['Carrageenan','None','Listed','Listed'],
 ['Artificial flavors','None','Listed','Not listed']
].map(row=><tr key={row[0]}><th scope="row">{row[0]}</th>{row.slice(1).map((cell,i)=><td className={i===0?'ours':''} key={i}>{cell}</td>)}</tr>)}</tbody></table></div><p className="fine sources">*Counts include individually named vitamins and minerals; grouped flavor ingredients count as one entry. Based on <a href="https://www.premierprotein.com/products/chocolate-protein-shake" target="_blank" rel="noreferrer">Premier Protein</a> and <a href="https://fairlife.com/core-power/chocolate-protein-shake/" target="_blank" rel="noreferrer">Fairlife Core Power</a> manufacturer labels, checked September 22, 2026. Formulas vary by flavor and may change. TNAT’s formula is in development. Ingredient count alone does not establish nutritional quality or safety.</p></section>}
export function TeamSection(){return <section className="team-section"><div className="shell section"><p className="eyebrow">For gyms, universities & athletic programs</p><div className="team-heading"><h2>Raise the standard.<br/>For the whole team.</h2><div><p className="section-description">Built from a college athlete’s perspective. Developed for the people responsible for what goes in the team fridge.</p><a className="button team-button" href="/wholesale">Wholesale & team inquiries <span aria-hidden="true">↗</span></a></div></div><div className="team-audiences"><article><span className="mono">01 / Athletic departments</span><p>Start a conversation about a future program partnership.</p></article><article><span className="mono">02 / Team dietitians</span><p>Discuss the formula, ingredient sourcing, and the testing information your program needs.</p></article><article><span className="mono">03 / Gyms & retailers</span><p>Register your interest in stocking TNAT when it launches.</p></article></div><p className="fine">Pre-launch conversations only. Product testing, third-party certification, and program-specific review are still pending. No university affiliation or endorsement is implied.</p></div></section>}
