const omissions=['Sucralose','Acesulfame potassium (Ace-K)','Stevia','Cellulose gum','Cellulose gel','Carrageenan','Artificial flavors','Phosphate stabilizer system','Added vegetable oil','Preservatives'];
const rows=[
 ['Protein per bottle','32g (estimated)','30g','26g'],
 ['Sweetening approach','Real palmetto honey','Sucralose + Ace-K','Monk fruit + stevia + Ace-K + sucralose'],
 ['Real honey','1 full serving','None listed','None listed'],
 ['Carrageenan','No','Listed','Listed'],
 ['Cellulose gum / gel','No','Both listed','Both listed'],
 ['Artificial sweeteners','No','Sucralose + Ace-K','Sucralose + Ace-K'],
 ['Artificial flavors','No','Listed','None listed'],
 ['Added phosphate stabilizers','No','Listed','None listed'],
 ['Added vegetable oil','No','Sunflower or soybean oil','None listed']
];
export function IngredientChoices({compact=false}:{compact?:boolean}){return <div className={`ingredient-choices${compact?' compact-choices':''}`}><div><p className="eyebrow">Our target formula</p><h3>What we choose<br/>not to use.</h3><ul className="omission-list">{omissions.map(item=><li key={item}><span>No</span> {item}</li>)}</ul></div><div className="honey-choice"><p className="eyebrow">What we choose instead</p><h3>A full serving.<br/>Of real honey.</h3><p>Palmetto honey brings the sweetness, signature flavor and carbohydrate fuel. We pair it with high-quality dairy protein and a straightforward ingredient list.</p>{!compact&&<p className="target-ingredients">Filtered water · Fat-free ultra-filtered milk · Whey protein concentrate · Palmetto honey · Pure vanilla extract · Sea salt.</p>}<p className="fine">Formula in development. These exclusions describe our target formula; commercial supplier subingredients and the final label are still being confirmed. Contains milk.</p><a className="text-link" href={compact?'/#label-difference':'/formula'}>{compact?'Compare the labels':'Explore the formula'} →</a></div></div>}
export function LabelComparison(){return <section className="label-comparison bone" id="label-difference"><div className="shell section"><div className="comparison-intro"><div><p className="eyebrow">Look Beeyond the Label.</p><h2>We chose honey.<br/><em>See the difference.</em></h2></div><p className="lead">Protein shakes don’t all get there the same way. beeast starts with real palmetto honey, dairy protein and a short, recognizable ingredient list.</p></div><IngredientChoices/><div className="comparison-heading"><h3>Turn the bottles around.</h3><p className="fine">Per bottle. Sizes differ. beeast figures are estimated; competitor figures are published label values.</p></div><p className="comparison-scroll-hint fine">Swipe or scroll sideways to compare all three.</p><div className="comparison-scroll" role="region" aria-label="Compare beeast, Premier Protein Vanilla and fairlife Core Power Vanilla" tabIndex={0}><table className="comparison-table"><caption className="visually-hidden">Ingredient comparison of beeast’s target formula and the published U.S. Vanilla labels of Premier Protein and fairlife Core Power.</caption><thead><tr><th scope="col">On the label</th><th scope="col" className="beeast-column">beeast<span>Palmetto Honey</span><small>12 fl oz · target formula</small></th><th scope="col">Premier Protein<span>Vanilla</span><small>11.5 fl oz</small></th><th scope="col">fairlife Core Power<span>Vanilla · 26g version</span><small>14 fl oz</small></th></tr></thead><tbody>{rows.map(([label,...values])=><tr key={label}><th scope="row">{label}</th>{values.map((value,i)=><td key={i} className={i===0?'beeast-column':undefined}>{value}</td>)}</tr>)}</tbody></table></div><div className="comparison-footnotes"><p className="fine">Ingredient panels as published by <a href="https://www.premierprotein.com/products/vanilla-protein-shake" target="_blank" rel="noreferrer">Premier Protein</a> and <a href="https://fairlife.com/core-power/vanilla-protein-shake/" target="_blank" rel="noreferrer">fairlife</a>, retrieved September 27, 2026. Comparison covers these specific U.S. Vanilla products; formulas can change. “None listed” means absent from the published ingredient statement.</p><p className="fine">beeast is a prototype, not a commercially validated finished product. 32g protein is estimated, pending testing. Honey contributes sugar and calories: our prototype estimates approximately 20g total sugars, including 16g added sugars from honey. This is an ingredient-choice comparison, not a claim of nutritional superiority.</p></div><div className="label-philosophy"><p>We’re not saying the ingredients in other shakes are unsafe. We’re saying we chose another way.</p><strong>Real honey. 32g protein. Nothing to hide.</strong></div></div></section>}
