const both='Core Power Chocolate · Premier Protein Chocolate';
const entries=[
 {name:'Carrageenan',on:both,text:'A seaweed-derived ingredient used to stabilize foods and help keep particles suspended.',detail:'The National Organic Standards Board recommended removal from the organic list in 2016. USDA renewed its listing in 2018 instead; the recommendation was not a ban.',url:'https://www.ams.usda.gov/rules-regulations/organic/petitioned-substances/carrageenan',source:'USDA review history'},
 {name:'Cellulose gum',on:both,text:'A cellulose-derived thickener and stabilizer, also called carboxymethylcellulose (CMC).',detail:'A controlled study published online in 2021 found changes in gut microbiota after 11 days at 15 g of CMC per day. It included 16 adults; the authors noted that this dose likely exceeds most people’s CMC intake. It did not test either shake or establish their health effects.',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9639366/',source:'Controlled-feeding study'},
 {name:'Cellulose gel',on:both,text:'Microcrystalline cellulose adds body and helps keep particles evenly suspended in a drink.',detail:'These are texture and stability functions. Its presence does not establish that heat destroyed a drink’s protein or that every shelf-stable drink needs it.',url:'https://www.iff.com/food-beverage/food-ingredients/hydrocolloids-texturants/cellulosics/avicel-microcrystalline-cellulose/',source:'Ingredient manufacturer: IFF'},
 {name:'Phosphate additives',on:'Premier Protein Chocolate',text:'The label names tripotassium phosphate, dipotassium phosphate, sodium hexametaphosphate, and magnesium phosphate, plus ferric orthophosphate in its vitamin and mineral blend.',detail:'Phosphates have formulation and nutritional uses. NIH reports approximately 70% absorption for phosphate additives, compared with 40–70% for phosphorus naturally present in food. Absorption alone is not a measure of a shake’s health effects.',url:'https://ods.od.nih.gov/factsheets/Phosphorus-HealthProfessional/',source:'NIH phosphorus fact sheet'},
 {name:'Sucralose + acesulfame potassium',on:both,text:'Both ingredient panels list these two artificial sweeteners. They provide sweetness in small amounts.',detail:'TNAT’s formula uses monk fruit extract as its only sweetener. The competing labels do not explain why their manufacturers selected a particular blend.',url:'https://www.fda.gov/food/food-additives-and-gras-ingredients-information-consumers/types-food-ingredients',source:'FDA ingredient functions'},
 {name:'Natural and artificial flavors',on:'Premier Protein Chocolate',text:'U.S. labeling rules allow flavor ingredients to be declared collectively as natural flavor, artificial flavor, or a combination.',detail:'That wording does not reveal the number of flavor compounds. TNAT’s chocolate formula uses cocoa and has no added flavor blend.',url:'https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfcfr/cfrsearch.cfm?fr=101.22',source:'21 CFR 101.22'},
 {name:'Lactase enzyme',on:'Core Power Chocolate',text:'Lactase breaks lactose into the simpler sugars glucose and galactose.',detail:'TNAT uses whey isolate, which generally contains less lactose than whey concentrate. That does not mean zero lactose: TNAT contains milk, and its finished-product lactose level has not been tested.',url:'https://www.fda.gov/food/generally-recognized-safe-gras/enzyme-preparations-used-food-partial-list',source:'FDA enzyme functions'},
 {name:'Milk protein concentrate + calcium caseinate',on:'Premier Protein Chocolate',text:'These are milk-derived protein ingredients. Milk protein contains whey and casein; calcium caseinate is derived from casein.',detail:'Whey and casein have different digestion profiles, and both supply essential amino acids. TNAT chooses whey isolate for its high protein concentration. A label cannot establish another manufacturer’s reasons for choosing its proteins.',url:'https://pubmed.ncbi.nlm.nih.gov/9405716/',source:'Whey and casein digestion study'},
];
export function LeftOut(){return <section className="left-out" id="what-we-left-out"><div className="shell section"><div className="left-out-heading"><div><p className="eyebrow">Read past the front of the bottle</p><h2>Every ingredient<br/>we didn’t add.</h2></div><p className="section-description">These ingredients appear on the chocolate labels below. Here’s what they do, what the evidence says, and how our seven-ingredient formula differs.</p></div><div className="omission-grid">{entries.map((item,i)=><article key={item.name}><span className="omission-index mono">{String(i+1).padStart(2,'0')}</span><div><p className="on-label">On: {item.on}</p><h3>{item.name}</h3><p>{item.text}</p><details><summary>Context & source <span aria-hidden="true">+</span></summary><p>{item.detail}</p><a href={item.url} target="_blank" rel="noreferrer">{item.source}</a></details></div></article>)}</div><div className="left-out-close"><p className="eyebrow">Our choice is a shorter label</p><p className="closing-statement">Seven named ingredients.<br/>A place in the fridge.</p><p>TNAT is being developed as a refrigerated shake, with a target of 45 days cold. Our formula has no gums, artificial sweeteners, or preservatives. Natural separation is expected. Shake well.</p><p className="fine">Shelf-life validation is pending. Refrigeration alone does not guarantee safety or remove the need for processing. Ingredient functions vary; not every ingredient above is required for shelf stability.</p></div><p className="fine omission-sources">Ingredient panels as published by <a href="https://fairlife.com/core-power/chocolate-protein-shake/" target="_blank" rel="noreferrer">Fairlife Core Power Chocolate (26g)</a> and <a href="https://www.premierprotein.com/products/chocolate-protein-shake" target="_blank" rel="noreferrer">Premier Protein Chocolate (30g)</a>, retrieved September 23, 2026. Formulas and serving sizes can change; check the bottle you buy. Ingredient presence alone does not establish harm or finished-product superiority.</p></div></section>}
