import {Header,Footer} from './components/Brand';
import WaitlistForm from './components/WaitlistForm';
import {ingredients,Numbers,Comparison,Waitlist,TeamSection,ColdPositioning} from './components/Content';
import {WheyBenefits} from './components/ProteinEducation';
import {Bottle} from './components/ProductMotion';
export default function Home(){return <><Header/><main id="main">
<section className="hero shell"><div className="hero-copy"><p className="eyebrow hero-tagline">The future of protein shakes</p><h1>Seven ingredients.<br/>Nothing else.</h1><p className="hero-description">A refrigerated chocolate whey isolate shake. In development for Florida’s college programs, teams, and training facilities.</p><p className="mono launch-note">Chocolate · 12 fl oz · Stuart, Florida</p><a className="button hero-team" href="/wholesale">For Teams & Facilities <span className="chevron" aria-hidden="true"/></a><WaitlistForm id="hero"/></div><Bottle/></section>
<section className="bone generation"><div className="shell section two-column"><div><p className="eyebrow">The generation of protein</p><h2>Built around<br/>the athlete.<br/>Start with the label.</h2></div><div><p className="section-description">Long shelf life has shaped the ready-to-drink aisle. Pick up a bottle and you may find gums, multiple sweeteners, and a label longer than you expected.</p><p className="section-description">TNAT starts with a different brief: whey isolate, seven named ingredients, and a place in the fridge. No proprietary blends. Every ingredient visible. Every choice explained.</p><p className="mono generation-fact">Seven ingredients. One chocolate shake.</p></div></div></section>
<section className="chocolate-field" id="ingredients"><div className="shell section ingredient-section"><div className="ingredient-intro"><p className="eyebrow">01 / The formula in development</p><h2>Everything in.<br/>Nothing hidden.</h2><p className="section-description">No gums, artificial sweeteners, or preservatives in our seven-ingredient formula.</p><div className="label-panel mono"><span>TNAT / Chocolate</span><strong>25g <small>Protein*</small></strong><strong>7 <small>Ingredients</small></strong><strong>150 <small>Calories*</small></strong><span>Keep refrigerated · Shake well</span><small>*Calculated nutrition targets. Not lab-tested.</small></div></div><div><ol className="ingredient-list">{ingredients.map(({name},i)=><li key={name}><span>{String(i+1).padStart(2,'0')}</span>{name}</li>)}</ol><details className="ingredient-detail"><summary>What each one does <span className="chevron down" aria-hidden="true"/></summary><div>{ingredients.map(({name,job})=><p key={name}><b>{name}.</b> {job}</p>)}</div></details><a className="text-link" href="/formula">Read the full formula <span className="chevron" aria-hidden="true"/></a><p className="fine allergen">Contains: milk. Made with coconut. Formula in development.</p></div></div></section>
<WheyBenefits/><Comparison/>
<section className="bone cold-promise"><div className="shell section"><ColdPositioning processLink/></div></section><Numbers/>
<TeamSection/>
<section className="founder-preview shell section"><figure className="action-photo"><img src="/assets/trevor-hofstra-lacrosse.jpg" alt="Trevor Natalie playing Division I lacrosse for Hofstra, wearing number 12" width="1290" height="2796" loading="lazy"/><figcaption className="mono">Trevor Natalie / Hofstra lacrosse</figcaption></figure><div><p className="eyebrow">From our founder</p><h2>I wanted the shake<br/>I thought I’d<br/>been drinking.</h2><p className="section-description">“I played Division I lacrosse at Hofstra and captained the team. When I finally read the label on my protein shake, I counted thirteen ingredients. I started TNAT because I wanted a shorter answer.”</p><a className="text-link" href="/about">Meet Trevor, founder & owner <span className="chevron" aria-hidden="true"/></a></div></section>
<section className="shake-ritual"><div className="shell section two-column"><div><p className="eyebrow">It’s a shake. Give it a shake.</p><h2>Cold bottle.<br/>Good shake.<br/>Chocolate moment.</h2></div><div><p className="section-description">Without gums, natural separation is expected. Shake the sealed bottle to bring the cocoa, cream, and protein back together before opening. It’s part of the formula, and part of the routine.</p><a className="text-link" href="/process#shake-well">The shake ritual <span className="chevron" aria-hidden="true"/></a></div></div></section>
<section className="bone"><div className="shell section faq-section"><div><p className="eyebrow">Before you ask</p><h2>A few straight<br/>answers.</h2><blockquote className="faq-quote">“A short label<br/>should tell you<br/>the whole story.”</blockquote><p className="mono">TNAT / Seven ingredients</p></div><div className="faq">{[
['Can I buy TNAT yet?','Not yet. Our chocolate formula is in development. There is no confirmed launch date, and we are not taking payments or preorders.'],
['How long will it last refrigerated?','Our target is 45 days cold for an unopened bottle. Shelf-life testing must confirm the final date, storage conditions, and instructions after opening.'],
['Is the nutrition final?','The targets are calculated estimates: 25g protein and 150 calories per 12 fl oz bottle. Finished-product testing is still pending.'],
['Is it third-party sport certified?','Not yet. Testing and certification are still ahead. Team staff should review the final product documentation before making a program decision.'],
['Where are you starting?','Florida, on purpose. We’re planning a refrigerated supply route for colleges and universities, pro and semi-pro teams, and independent gyms and training facilities. Service areas and delivery terms are still being developed.'],
['Can individual customers join the waitlist?','Yes. Teams and facilities are our first focus, and individual customers are welcome to follow our chocolate launch.'],
['What about other flavors?','Chocolate comes first. Vanilla is planned next; its formula and launch date are not set.']
].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section><Waitlist/>
</main><Footer/></>}
