import {Header,Footer} from '../components/Brand';
import {Waitlist,ColdLife,ColdPositioning} from '../components/Content';
export const metadata={title:'The planned process'};
export default function Process(){return <><Header/><main id="main">
<section className="shell page-hero process-hero"><div><p className="eyebrow">The process / In development</p><h1>Made cold.<br/>Kept cold.<br/>Shaken well.</h1><p className="section-description">A creamy chocolate protein shake, from the ingredients to the last sip. We’re developing it for the refrigerator, with a target of 45 days cold. The process and shelf life still need validation.</p><a className="text-link" href="#shake-well">Why the shake matters <span className="chevron down" aria-hidden="true"/></a></div><ColdLife/></section>
<section className="flavor-band cold-promise"><div className="shell section"><ColdPositioning/></div></section>
<section className="bone"><div className="shell section process-list"><p className="eyebrow">Our development plan</p>{[
['01','Build the shake.','Blend the seven ingredients in development. Whey isolate supplies the protein, coconut cream brings body, and cocoa makes it chocolate. We’re developing a creamy, drinkable shake with a balanced finish.'],
['02','Bring it together.','Homogenize to help disperse the water, protein, cocoa, and coconut cream. Sunflower lecithin helps fat and water mix. Without gums, some settling and natural separation are expected; texture and stability still need testing.'],
['03','Bottle and seal.','Move into suitable packaging at a licensed production facility. Our co-packing partner has not yet been selected.'],
['04','Apply pressure.','Evaluate high pressure processing (HPP) as part of a validated food-safety process. Pressure settings, holding times, and product compatibility must be established by qualified specialists.'],
['05','Keep it cold.','Plan for refrigerated storage and distribution. We’re targeting 45 days cold for an unopened bottle. Shelf-life studies must confirm the final shelf life, storage conditions, and instructions after opening.']
].map(([n,title,body])=><article key={n}><span className="mono">{n}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></section>
<section className="shake-ritual" id="shake-well"><div className="shell section"><p className="eyebrow">The final step is yours</p><div className="team-heading"><h2>Shake well.<br/>It’s in the name.</h2><p className="section-description">Cocoa can settle. Cream and water can separate. A good shake helps bring the ingredients back together for the texture we’re working toward. No gums in the formula means this little ritual matters.</p></div><ol className="ritual-steps"><li><span className="mono">01 / Cold</span><h3>Take it from the fridge.</h3><p>TNAT is being developed as a refrigerated shake. Follow the final label’s storage instructions when it launches.</p></li><li><span className="mono">02 / Shake</span><h3>Keep it sealed. Shake well.</h3><p>Before opening, give the bottle a good shake to mix the protein, cream, and cocoa.</p></li><li><span className="mono">03 / Enjoy</span><h3>Open. Sip. Make it yours.</h3><p>After your workout, between plans, or as part of your everyday routine. Follow the label’s instructions after opening.</p></li></ol><p className="fine">Planned serving experience. Final texture and directions will be confirmed during product development.</p></div></section>
<section className="shell section two-column"><div><p className="eyebrow">Where we stand</p><h2>The work<br/>before the launch.</h2></div><div className="prose"><p>The formula is at the benchtop stage. Production, safety validation, shelf-life studies, and finished-product nutrition testing are still ahead.</p><p>45 days cold is our development target, not an established use-by period. We’ll share confirmed details as testing progresses.</p></div></section><Waitlist/></main><Footer/></>}
